---
- hosts: all
  become: yes
  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Iniciar el servicio de Apache
      service:
        name: apache2
        state: started

    - name: Copiar archivos HTML
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
        mode: '0644'

